version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: proctor_db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db:
